In [1]:
import numpy as np

In [2]:
arr = np.array([1, 2, 3])

In [3]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])

In [4]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [5]:
np.ones((2, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [6]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [7]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [8]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [9]:
np.random.rand(3, 2)

array([[0.55633687, 0.3705065 ],
       [0.77010586, 0.3181967 ],
       [0.58802908, 0.45614043]])

In [10]:
np.random.randn(3, 2)

array([[ 0.60755064,  2.45770153],
       [-0.33626614,  1.33732095],
       [ 0.07367998,  0.1765867 ]])

In [11]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

In [12]:
print(arr.shape)

(2, 3)


In [13]:
print(arr.ndim)

2


In [14]:
print(arr.size)

6


In [15]:
print(arr.dtype)

int64


In [16]:
a = np.array([1, 2, 3])

In [17]:
b = np.array([4, 5, 6])

In [18]:
a + b

array([5, 7, 9])

In [19]:
a * b

array([ 4, 10, 18])

In [20]:
np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

In [21]:
A = np.array([[1, 2], [3, 4]])

In [22]:
B = np.array([[5, 6], [7, 8]])

In [23]:
np.dot(A, B)

array([[19, 22],
       [43, 50]])

In [24]:
A @ B

array([[19, 22],
       [43, 50]])

In [25]:
arr = np.array([1, 2, 3, 4])

In [26]:
arr.sum()

np.int64(10)

In [27]:
arr.mean()

np.float64(2.5)

In [28]:
arr.max()

np.int64(4)

In [29]:
arr.min()

np.int64(1)

In [30]:
arr.std()

np.float64(1.118033988749895)

In [31]:
arr = np.array([1, 2, 3, 4, 5])

In [32]:
arr[0]

np.int64(1)

In [33]:
arr[1:4]

array([2, 3, 4])

In [34]:
arr[::2]

array([1, 3, 5])

In [35]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

In [36]:
arr[0, 1]

np.int64(2)

In [37]:
arr[0, 1]

np.int64(2)

In [38]:
arr[:, 1]

array([2, 5])

In [39]:
arr[1, :2]

array([4, 5])

In [40]:
arr = np.array([1, 2, 3, 4, 5])

In [41]:
mask = arr > 3

In [42]:
arr[mask]

array([4, 5])

In [43]:
arr = np.arange(6)

In [44]:
arr.reshape(2, 3)

array([[0, 1, 2],
       [3, 4, 5]])

In [45]:
a = np.array([1, 2])

In [46]:
b = np.array([3, 4])

In [47]:
np.concatenate((a, b))

array([1, 2, 3, 4])

In [48]:
np.vstack((a, b))

array([[1, 2],
       [3, 4]])

In [49]:
np.hstack((a, b))

array([1, 2, 3, 4])

In [50]:
a = np.array([1, 2, 3])

In [51]:
a + 5 # [6, 7, 8]

array([6, 7, 8])

In [52]:
np.save('array.npy', arr)

In [53]:
loaded_arr = np.load('array.npy')